from abc import ABC, abstractmethod
import json
from faos.services.report.models import Report

class BaseRenderer(ABC):
    """
    Abstract base class for all Report Renderers.
    """
    @abstractmethod
    def render(self, report: Report) -> str:
        pass


class MarkdownRenderer(BaseRenderer):
    """
    Renders a Report object into a formatted Markdown string.
    """
    def render(self, report: Report) -> str:
        lines = []
        lines.append(f"# {report.title}")
        if report.summary:
            lines.append(f"\n> {report.summary}")
            
        for section in report.sections:
            lines.append(f"\n## {section.title}")
            lines.append(section.content)
            
            if section.charts:
                lines.append("\n**Charts:**")
                for chart in section.charts:
                    lines.append(f"- {chart.get('title', 'Chart')}")
                    
            if section.tables:
                lines.append("\n**Tables:**")
                for table in section.tables:
                    lines.append(f"- {table.get('title', 'Table')}")
                    
        lines.append("\n---\n*Report generated by FAOS Report Service*")
        
        return "\n".join(lines)


class JsonRenderer(BaseRenderer):
    """
    Renders a Report object into a JSON string.
    """
    def render(self, report: Report) -> str:
        return json.dumps(report.model_dump(), indent=2, ensure_ascii=False)
