import logging
import json
from typing import Dict, Any

from faos.services.report.models import ReportRequest, ReportResponse

logger = logging.getLogger(__name__)

class ReportService:
    """
    Report Service is responsible for final output generation.
    It takes context data and formats it into the requested structure.
    """
    def __init__(self):
        logger.info("ReportService initialized")

    async def generate(self, request: ReportRequest) -> ReportResponse:
        logger.info(f"ReportService generating report for task {request.task_id} in {request.format} format")
        
        try:
            if request.format.lower() == "markdown":
                content = self._generate_markdown(request.context_data)
                return ReportResponse(format="markdown", content=content)
            elif request.format.lower() == "json":
                content = self._generate_json(request.context_data)
                return ReportResponse(format="json", content=content)
            else:
                error_msg = f"Unsupported report format: {request.format}"
                logger.error(error_msg)
                return ReportResponse(format=request.format, content="", status="failed", error=error_msg)
        except Exception as e:
            logger.error(f"Failed to generate report: {e}")
            return ReportResponse(format=request.format, content="", status="failed", error=str(e))

    def _generate_markdown(self, context_data: Dict[str, Any]) -> str:
        analysis = context_data.get("analysis", {})
        decision = context_data.get("decision", {})
        
        symbol = analysis.get('symbol', 'UNKNOWN')
        price = analysis.get('price', 0.0)
        target = analysis.get('target_price', 0.0)
        sentiment = analysis.get('sentiment', 0.0)
        
        action = decision.get('action', 'UNKNOWN')
        confidence = decision.get('confidence', 0.0) * 100
        strategy = decision.get('strategy', 'N/A')
        risk = decision.get('risk', 'N/A')
        reason = decision.get('reason', 'N/A')
        
        report_md = f"""# FAOS Analysis Report for {symbol}

## Market Data
- **Current Price**: ${price:.2f}
- **Target Price**: ${target:.2f}

## Analysis Summary
- **News Sentiment**: {sentiment:.2f}

## Investment Decision
- **Action**: **{action}**
- **Confidence**: {confidence:.1f}%
- **Strategy**: {strategy}
- **Risk Level**: {risk}
- **Reason**: {reason}

---
*Report generated by FAOS Report Service*"""
        return report_md

    def _generate_json(self, context_data: Dict[str, Any]) -> Dict[str, Any]:
        return {
            "metadata": {
                "generator": "FAOS Report Service"
            },
            "data": context_data
        }
