import asyncio
from faos.services.skill.base import BaseSkill
from faos.services.skill.models import SkillRequest, SkillResponse, SkillManifest
from faos.services.reasoning.service import ReasoningService
from faos.services.reasoning.models import ReasoningRequest

class FetchDataSkill(BaseSkill):
    @property
    def manifest(self) -> SkillManifest:
        return SkillManifest(
            id="stock.quote.mock",
            name="Mock Quote Skill",
            capability="FetchData",
            description="Mock implementation of fetching quote data"
        )
        
    async def execute(self, request: SkillRequest) -> SkillResponse:
        await asyncio.sleep(0.5)
        symbol = request.parameters.get("symbol", "AAPL")
        output_data = {"symbol": symbol, "price": 175.5, "volume": 50000000}
        
        # Skill writes to ExecutionContext as per architecture
        request.context.add_provider_output("quote", output_data)
        return SkillResponse(status="success", output={"data_type": "quote"})


class FetchNewsSkill(BaseSkill):
    @property
    def manifest(self) -> SkillManifest:
        return SkillManifest(
            id="stock.news.mock",
            name="Mock News Skill",
            capability="FetchNews",
            description="Mock implementation of fetching news data"
        )
        
    async def execute(self, request: SkillRequest) -> SkillResponse:
        await asyncio.sleep(0.5)
        symbol = request.parameters.get("symbol", "AAPL")
        news_data = [
            {"title": f"New product launch for {symbol}", "sentiment": 0.8},
            {"title": f"{symbol} stock reaches new high", "sentiment": 0.7}
        ]
        
        request.context.add_provider_output("news", news_data)
        return SkillResponse(status="success", output={"data_type": "news"})


class AnalyzeSkill(BaseSkill):
    def __init__(self, reasoning_service: ReasoningService):
        self.reasoning_service = reasoning_service
        
    @property
    def manifest(self) -> SkillManifest:
        return SkillManifest(
            id="stock.analyze.reasoning",
            name="Reasoning Analyze Skill",
            capability="Analyze",
            description="Uses ReasoningService to analyze stock"
        )
        
    async def execute(self, request: SkillRequest) -> SkillResponse:
        reasoning_req = ReasoningRequest(
            task_id=request.task_id,
            context_data=request.context.provider_outputs
        )
        response = await self.reasoning_service.analyze_context(reasoning_req)
        
        request.context.add_result("analysis", response.insights)
        return SkillResponse(status="success", output=response.insights)


class GenerateReportSkill(BaseSkill):
    @property
    def manifest(self) -> SkillManifest:
        return SkillManifest(
            id="stock.report.markdown",
            name="Markdown Report Skill",
            capability="GenerateReport",
            description="Generates markdown report from analysis"
        )
        
    async def execute(self, request: SkillRequest) -> SkillResponse:
        await asyncio.sleep(0.5)
        analysis = request.context.results.get("analysis", {})
        
        report_md = f"""# FAOS Analysis Report for {analysis.get('symbol', 'UNKNOWN')}

## Market Data
- **Current Price**: ${analysis.get('price', 0.0):.2f}
- **Target Price**: ${analysis.get('target_price', 0.0):.2f}

## Analysis Summary
- **News Sentiment**: {analysis.get('sentiment', 0.0):.2f}
- **Recommendation**: **{analysis.get('recommendation', 'HOLD')}**
- **Confidence**: {analysis.get('confidence', 0.0) * 100:.1f}%

---
*Report generated by FAOS Execution Engine v5.0*"""
        
        request.context.add_result("report", report_md)
        return SkillResponse(status="success", output={"report_preview": report_md[:100] + "..."})
