from pydantic import BaseModel, Field
from typing import Dict, Any, List

class ReasoningRequest(BaseModel):
    task_id: str = Field(..., description="ID of the task this reasoning belongs to")
    context_data: Dict[str, Any] = Field(..., description="The data from ExecutionContext to analyze")
    prompt_template: str = Field(default="", description="The template to guide the reasoning")

class ReasoningResponse(BaseModel):
    task_id: str
    insights: Dict[str, Any] = Field(default_factory=dict, description="Structured insights generated by LLM")
    confidence: float = Field(default=0.0, description="Confidence score of the reasoning")
    raw_response: str = Field(default="", description="Raw text response from LLM")
    usage: Dict[str, int] = Field(default_factory=dict, description="Token usage metrics")
